### ISSUE TITLE
Can't sync Dropbox until you sign in and move it to a supported file system

### ISSUE THREAD

**Issue by jgarciao** [flathub/com.dropbox.Client#20]
I'm using this flatpak in fedora silverblue. My home partition is formatted in ext4 but starting today Dropbox is not working complaining about being unsupported format

More info and a hack to make it work here
https://popey.com/blog/posts/fixing-broken-dropbox-sync-support.html

**Comment by wjt** [comment]
This is strange because this package works fine for me on two systems with `ext4` `/home`:

* Fedora 29 (non-Silverblue) with `/dev/mapper/gelf-home on /home type ext4 (rw,relatime)` (the partition is within a LVM logical volume, whose PV is on a LUKS partition)
* Endless (unreleased master version) with `/home` a symlink to `/sysroot/home`; `/sysroot` is the root directory of an `ext4` volume

The script we run at Endless to monitor the latest version of the extra-data has been notifying me of lots of version updates (including one rollback to the previous major version) over the past few days – perhaps due to the roll-out of this "feature"? I just pushed an update to 63.4.107 which has been unchanged as the latest version for 24 hours. Could you check the problem still happens with that version? Is there anything else "weird" about your `/home`?

**Comment by jgarciao** [comment]
I've solved the problem of Dropbox not working in Fedora Silverblue when using an ext4 partition:

- My /etc/fstab mounts the home partition in /var/home
``` 
/dev/mapper/fedora-root /                       ext4    defaults        1 1
UUID=f5c6e694-f0ac-44c4-9150-2a97aac32r34 /boot                   ext4    defaults        1 2
UUID=26b291ca-4c41-3bbe-b246-28012a74846c /boot/efi               hfsplus defaults        0 2
UUID=fb6a6c9f-64ad-47w8-91e4-v58227797961 /var/home               ext4    defaults        1 2
```
- And there is a symlink from /home to /var/home
- Dropbox said /home/jorge/Dropbox wasn't ext4. I though maybe there was a problem with the symlink
- So I configured Dropbox to use /var/home/jorge/Dropbox instead and that fixed the issue!

**Comment by wjt** [comment]
Interesting. On Endless we put home directories in `/sysroot/home` with symlinks from `/home` and `/var/home` (for historical reasons) but I have not had this problem. I think it's because the user account actually has its `$HOME` configured to be `/sysroot/home/$USER` rather than going via the symlink.

**Comment by jgarciao** [comment]
In Silverblue `$HOME` is `/home/jorge`

**Comment by averyfreeman** [comment]
I just wanted to mention I ran into what I believe was the same problem on SilverBlue so many years later, it was complaining that the file system wasn't supported.

This is really confusing these days, because Dropbox shouldn't have file system type constraints anymore. It should be noted my `/var/home` is btrfs, which is default for SilverBlue now in Fedora 35.

However, I don't believe the issue has to do with file system at all, but location of home folder: 

Instead of using selecting `/home/<username>` when I got the installation unsupported file system warning, I "moved" the Dropbox location to `/var/home/<username>` (where it automatically creates or finds the folder named  'Dropbox')

It seems likely this is an upstream issue, so I apologize for putting this here, but I imagine this closed issue is a logical first place to look who are troubleshooting, since the issue only seems to happen with the flatpak version.
