### ISSUE TITLE
Dropbox uses Gwenview instead of Dolphin file manager.

### ISSUE THREAD

**Issue by drhedberg** [flathub/com.dropbox.Client#8]
Fresh install of Manjaro KDE and installed Dropbox Flatpak.  When it boots up Gwenview opens my Dropbox folders rather than my default file manager Dolphin.  I fixed this issue by changing my default file manager to Gwenview and then back to Dolphin.

The only problem now is that Dolphin opens up to my Dropbox folders when I boot my computer or restart Dropbox.

Is there any way to stop Dolphin from automatically opening my Dropbox folders?

Although I fixed the Gwenview issue, this should be looked at as well.

Thanks for all your work on this Flatpak!  Much appreciated.

**Comment by wjt** [comment]
How did you arrange for Dropbox to be auto-started? On #13 I added a check to the launcher script that detects the $DESKTOP_AUTOSTART_ID variable, which is set by `gnome-session` only when autostarting an app (due to its .desktop file being symlinked into ~/.config/autostart). I don't know whether whatever KDE does to auto-start applications sets the same variable, or if there's some other way to detect this case.

**Comment by drhedberg** [comment]
Yes, Dolphin still opens automatically when I boot into the system.

**Comment by aldevel** [comment]
I use KDE neon and I have the very same issue except I had to set autostart manually for dropbox because "start Dropbox on system startup" radio button selection is lost on every restart. Also on my first pc dropbox started with Filelight the second one started with Cervisia what is interesting why is it can't see which one is the default on the system. Although I was able to solve this mimetype issue thanks to drhedbeg's solution, I don't understand why Flatpak's Dropbox won't start in the normal way I mean in the background with a single system tray icon, why is it wan't to open anything?

**Comment by drhedberg** [comment]
I decided to uninstall Dropbox flatpak and install it from the Arch User Repository and it's working fine on my Manjaro KDE system.  One would think that starting an application properly would be the most basic thing but I guess flatpak is still in its infancy.

**Comment by wjt** [comment]
When the next build hits the Flathub repo in a few hours, both these issues should be solved. Please reopen if not.
