### ISSUE TITLE
Include dropbox-filesystem-fix

### ISSUE THREAD

**Issue by ranisalt** [flathub/com.dropbox.Client#83]
As already discussed on other issues, Dropbox has artificially limited support to non-ext4 filesystems, but the app works perfectly otherwise. Could this flatpak include [dropbox-filesystem-fix](https://github.com/dark/dropbox-filesystem-fix), a patch that just skips that ridiculous check and allows Dropbox to run on other filesystems?

**Comment by soredake** [comment]
https://github.com/flathub/com.spotify.Client/blob/master/com.spotify.Client.json#L110-L123
https://github.com/flathub/com.spotify.Client/blob/master/spotify-bin

**Comment by averyfreeman** [comment]
I also came on to report this is complaining about btrfs filesystem on newly installed Silverblue

I unpacked a dropbox rpm and ran the binary and it doesn't complain at all.  It looks like the source used for flathub is quite outdated.

**Comment by wjt** [comment]
The source used for Flatpak is kept up-to-date automatically so I don't think it being out of date is the problem

**Comment by averyfreeman** [comment]
Yes, this is a very strange issue.  I ended up installing through RPM, which was unfortunate because machine runs silverblue OS.

I installed the flatpak through flathub on another system running zfs and should have experienced similar installation errors due to filesystem, but did not.  Also, others have confirmed not experiencing issues on Fedora BTRFS subreddit. 

The QT libraries used in the Dropbox I installed through flathub on the Silverblue machine that complained it could not use btrfs looked noticeably dated.  Is there some way an older copy of the flatpak might be installed rather than the latest one?

If flathub is keeping older copies of the dropbox flatpak and installing them for some reason by default on ostree OS, is there a way to purge those prior to 2019 elimination of the filesystem discrepancy?

Thanks

**Comment by wjt** [comment]
Flathub tracks the latest packages from Dropbox. Dropbox bundles an ancient Qt.

Dropbox from Flathub works on most mainstream Linux filesystems. The linked repo has not been touched for 4 years and its README contains the following:

> Please note: I have stopped using the official Dropbox Linux client, so this project is in maintenance mode, and it will not receive any more patches from me. I may not be able to help you debug new breakages, nor test any changes.
